### ISSUE TITLE
take screenshot

### ISSUE THREAD

**Issue by lainz** [bgrabitmap/lazpaint#110]
take a screenshot with lazpaint.

**Comment by rchastain** [comment]
Hello!

Often I take screenshot of all the screen with Print Screen touch, and after that I paste the picture in Paint and crop the image. Sometimes I try to use LazPaint instead of Paint, but I find it less easy. Probably I don't know how to use LazPaint. For example, in Paint, to crop the image, I just drag the borders of the picture and see how many pixels I remove. In LazPaint I have to change canvas size through the menu, choose an anchor, type the desired width... Is there another method?

By the way, there is a nice little screenshot tool, based on BGRABitmap, but it's a little buggy. It would need to be revised.
https://github.com/adnan360/snapping-tool

Regards.

Roland

**Comment by circular17** [comment]
Hi Roland,

There is an issue with floating point coordinates selection that I am fixing in next release. That may be an issue for you.

Though I am not sure I understand. In the status bar, you have the coordinates of the selection rectangle. Is that not sufficient? Or maybe it is a matter of zoom to see where the selection is?

**Comment by rchastain** [comment]
Hello Johann! Thank you for your answer. Don't pay too much attention to what I said. I wanted to contribute to the discussion about screenshots. I retried once again after reading your message. I see nothing to improve: it's perfect. The problem is that I don't use LazPaint often enough.

**Comment by circular17** [comment]
Alright then.

**Comment by rchastain** [comment]
In Linux Mageia there is a tool for screenshots named Spectacle. A nice feature is that you can take a screenshot of the active window. There are options to include/exclude mouse pointer, include/exclude window title bar and borders. Maybe an idea for LazPaint?

Regards.

Roland

**Comment by circular17** [comment]
cropping tool discussion : https://github.com/bgrabitmap/lazpaint/issues/130

**Comment by circular17** [comment]
on Windows, Shift-Win S is very handy. On MacOS it is Shift-Cmd 4. So I think I won't implement it.
