### ISSUE TITLE
Splash Logo

### ISSUE THREAD

**Issue by lainz** [bgrabitmap/lazpaint#114]
When running LazPaint, display a logo with the icon and version number. Display it just a few milliseconds-

**Comment by circular17** [comment]
Hmm I don't know. I find it slows down a bit the startup.

**Comment by lainz** [comment]
Ok no problem. Maybe all image editors include that because they're slow loading, but LazPaint loads quickly.

**Comment by circular17** [comment]
Yeah, probably.

**Comment by c-sanchez** [comment]
Yeah, although that looks "nice" I think is nicer wich opens "instantly" without show any splash :P
Comen on, reading preferences, loading scripts, loading loader system, really? zzZzZZz
![photoshop splash](https://pbs.twimg.com/media/ClqaDAJWYAAv4OK.jpg)
![gimp splash](https://149366088.v2.pressablecdn.com/wp-content/uploads/2016/08/default-stock-gimp-splash-screen.jpg)
_Please wake me up when they finish loading._

But ok, now seriusly, an splash screen make the startup slow, and have no much sense if the app can start quickly.
**I really hope this never changes in LazPaint.**

However, we can see the splash screen as an opotunity to show some art, and make looks the program more "professional" at same time.

With that in mind, maybe show the splash screen in other place?
Maybe make the **about window** in an **splash screen** can be nice indeed :P

By example Gimp have a simple "about" with an animation for names, is simple but good.
![gimp about gig](https://i.ibb.co/4KdGwSD/gimp-about.gif)

A quick (ugly) splash example :P
![lazysplash](https://i.ibb.co/d4NbscZ/simple-splash-example.png)
Another idea that comes to mind is, since we have the 3D LazPaint icon thanks to Lainz, maybe just show the icon in 3D, and makes a rotation to see the backside and there have the text info.

**Comment by circular17** [comment]
Haha that's indeed a "splash" screen!

Regarding the about box, I believe few people look at it. Definitely a splash screen is a way to show something every time. Another possibility is to have something in the work area of LazPaint window until a new image is created or opened.

**Comment by circular17** [comment]
In fact I am thinking that people are not very much aware of the donation thing. So maybe the splash screen might help with that?

**Comment by c-sanchez** [comment]
Heh I'm aware about donation, indeed yesterday I was thinking of donating a bit, but I can't for now, sorry! I will like send you something later anyway.
I'm not sure about how much can help a splash screen for donation purposes, but it might be good to improve that.

one thing I was thinking about is that it would be okay if you add other donation options in addition to paypal.

* Paypal

* Critocurrency addresses, I think with the 5 most popular will be ok
(bitcoin, bitcoin cash, litecoin, dogecoin, ethereum)

* Coinbase email
is one of the most widely used online wallets, in addition to the addresses of cryptocurrency, we can use mail to send and receive money directly, so avoid the process of confirmation of criptocurrency.

So I think could be nice if you add maybe a "donations" section in the about window, splash or whatever heh

I like the idea the add some in the work area, however  I wonder how can you make this looks good and looks as "empty space" at same time, so as not to cause the misconception that there's an open image.

**Comment by circular17** [comment]
It's ok Carlos you're already contributing in your way.

I see about using other donation methods, though for now I receive one donation every 3 years so I am not going to setup something else for now.

I understand the idea about the image confusion. Though the work area and the empty image have a specific look. Maybe if it is animated, or just a bar on top of it, that would not be confused.

**Comment by circular17** [comment]
For now, it is not necessary to have a splash logo, and there is a donate button now on the toolbar from the start.
