### ISSUE TITLE
Files are not associated with the application

### ISSUE THREAD

**Issue by Orion8V** [bgrabitmap/lazpaint#326]
LP_02
Summary				Files are not associated with the application
Project				LazPaint
Component			Installer, Аpplication
Version				7.1.16
Severity				Major
Priority				Defined by the project manager
Status				New
Author				Victor D., dvvbox@mail.ru
Assigned To			-
Environment			Windows 7 32-bit SP1, CPU Intel Core 2 Quad Q6700 2,66GHz, RAM 4Gb, GPU Gigabyte GeForce GTX 660 Ti, HDD WD Caviar Blue 640Gb
Steps to Reproduce		When installing, associate .jpg files with the application
					In OS Explorer DblClick on a .jpg file"
Result				Application does not download file
Expected Result		Application download file
Attachment			-

**Comment by lainz** [comment]
Hi, since Windows 7 when associating a file extension with an installer not directly sets the association. It allows you to choose Open With... LazPaint and list in the list of applications that can handle for example .jpg files.

In the end the user must associate .jpg with LazPaint, is the way Windows does it nowdays. For example on Windows 10 it asks the user if he wants to keep using photo viewer or switch to LazPaint.

This is good because in the past say Windows XP or older, any application can change the file associations and break your settings.
