### ISSUE TITLE
Objects in the script field do not work

### ISSUE THREAD

**Issue by GoncharovaNatalia** [bgrabitmap/lazpaint#337]
Full description - Objects in the script field do not work, a message pops up “Expected Python version 3 but 0 found”
Reproducibility – always. 
Severity – Major.
Environment – Windows 10 (64-bit), LazPaint 7.1.6 (64-bit)
Steps To Reproduce - Any file is open. Select "Script"- channels – split HSL.
Additional Information – report4.mp4
It may be necessary to make a version of the program without scripts so that users do not have a bad impression of the program if similar errors constantly pop up in it.

https://user-images.githubusercontent.com/92689012/137639782-b0e1db51-2bbf-46b9-98d3-05265e991797.mp4

**Comment by circular17** [comment]
The download buttons helps to find the binaries of Python to install. I am thinking of providing an alternative way of handling scripts that would not require to install Python.

I prefer not to remove the menus for the scripts, because they can be useful.

Related to https://github.com/bgrabitmap/lazpaint/issues/192 and https://github.com/bgrabitmap/lazpaint/issues/510
