### ISSUE TITLE
The print function does not work correctly

### ISSUE THREAD

**Issue by Gos1k** [bgrabitmap/lazpaint#376]
**1) Summary:** The print function does not work correctly

**2) Description:** When using the print function, the printer prints a blank page, regardless of what is in the document

**3) Environment:**

 Windows 10 Pro x64, Build 19043.1320, Version  21H1

LazPaint 7.1.6, 64-bit, portable
 
Printer: Kyocera FS – 1035MFP

**4) Steps to reproduce**

Press File
Press Print 

**5) Expected behavior**
The printer should print the specified image

**6) Actual behavior**
The printer prints a blank page

**Comment by circular17** [comment]
That's surprising. Have you tried another printer, for example Print To PDF?

**Comment by lainz** [comment]
I have an HP DeskJet Ink Advantage 2135 and I oftenly print with LazPaint without issues.

**Comment by lainz** [comment]
Notice that my printer uses ink and the printer of Gos1k uses toner.

**Comment by melchiorrecaruso** [comment]
I just wanted to report that I'm having the same issue.

LazPaint initially printed correctly, but after a few months, it started printing blank pages.


The printer I use in the office is a RICOH IM C2000.

The same images print correctly with other graphic programs like Microsoft Paint or Gimp.

Regarding virtual printers, Adobe PDF doesn't work, but Microsoft Print to PDF works fine.


Operating system: Windows 10 Pro 22H2


Regards

**Comment by melchiorrecaruso** [comment]
I think the problem is related to transparency & Windows because it started when I began to cut out the images.

On Linux (Fedora 40), both attached images are printed correctly.
Later, I will try on another PC with Windows 10.

Regards

![OK](https://github.com/bgrabitmap/lazpaint/assets/9728079/70313a8a-854b-464c-9a86-87fc06bde874)
![KO](https://github.com/bgrabitmap/lazpaint/assets/9728079/7c42edff-0806-405a-a52a-e1c2b584b47d)

**Comment by melchiorrecaruso** [comment]
I believe I've figured out why the problem occurs at the office but not at home: not all printers support transparency.

Now that I've connected my work PC to the home printer, the issue has disappeared.
Nevertheless, I think this problem should be addressed because it doesn't happen with Gimp or Paint.

Best regards,
Melchiorre

**Comment by circular17** [comment]
Hi Melchiorre!

Thank you very much for your feedback. Your detailed explanation seems to point towards a solution. Would that be to fill the background with white before printing?

Regards

**Comment by melchiorrecaruso** [comment]
You're welcome!

Yes, the solution could be to fill the background with white before printing.

**Comment by circular17** [comment]
Thanks, I'm adding this issue to the next release

**Comment by melchiorrecaruso** [comment]
The solution for this problem also resolves the third issue in report #584, and the check for empty images can be removed.

Regards

**Comment by circular17** [comment]
I've applied the change on dev branch.

**Comment by melchiorrecaruso** [comment]
In my last message, I wrote that the check for the empty images can be removed, but I should have written must be removed. Printing a empty page raises an exception. 

I apologize for the translation error.
Best regards
