### ISSUE TITLE
Moving the selected object to a new layer forms an artifact on the background

### ISSUE THREAD

**Issue by GHjaz** [bgrabitmap/lazpaint#445]
Priority: Minor

Environment: Windows 10 (x64), LazPaint 7.1.6 (64-bit)

Description:
Moving the selected object to a new layer forms an artifact on the background

Steps to reproduce:

1. Create object on Layer 1 
2. Select object
3. Move selected object on new layer
4. Rotate or replace object on new layer
Actual result: The trace of the selection appears in the background of the layer
Expected result: The trace should not appear

https://user-images.githubusercontent.com/43647906/144750996-75aae703-8a78-46fd-9b9e-5c3538e71977.mp4

**Comment by circular17** [comment]
Yes, this happens when Progressive button is down (in the top toolbar). In this mode, the selection border is partially selected, so that you get a kind of antialiasing. The when it is copied and merged with the layer, the pixels are not completely black on the borders (either transparent or merged with the white background). Then when selecting with the magic wand again, there is a difference of color, so the border again is not completely selected.

You need to deselect the progressive mode to avoid such effect.

Anyway, as this is a vector shape, it is better to select it with the shape editing tool (just above rectangle below flood fill tool). Then when you copy and paste you will keep the shape as it is and be able to modify it like moving points around, change color etc.
