### ISSUE TITLE
Crash after image processing

### ISSUE THREAD

**Issue by vexillia** [bgrabitmap/lazpaint#529]
Lazpaint: lazpaint 7.2.2_linux64.deb
OS: xUbuntu 22.04.1 (fresh install)
Mono: version 6.12.0.182 (tarball Tue Jun 14 22:35:00 UTC 2022) via official ppa

Lazpaint opens OK.  I can open an image file and change the canvas size but after resampling the program crashes completely.  

Opening app via terminal gives a error message that suggests it's a mono failure (hence the updated version) and sometimes I get a error file (json) too.

Same behaviour with standard version of mono and either 7.22 or 7.1.6 too.

What am I missing?

**Comment by circular17** [comment]
Hello!

LazPaint doesn’t use Mono so I don’t understand how that would be the issue.

Can you give more details on the error you’re getting and the exact steps to reproduce?

If you can, you can debug it with Lazarus (I can explain how to) to get more detailed information or I will do that.

**Comment by vexillia** [comment]
On start from terminal:

`Gtk-Message: 08:14:59.115: Failed to load module "xapp-gtk3-module"

(lazpaint:450873): dbind-WARNING **: 08:14:59.120: Couldn't connect to accessibility bus: Failed to connect to socket /root/.cache/at-spi/bus_0.0: Permission denied
`
After crash:

`[FORMS.PP] ExceptionOccurred 
  Sender=EAccessViolation
  Exception=Access violation
  Stack trace:
  $0000000000000000
  $000055E7A044E264
  $000055E7A02521A8
  $000055E7A0251E37
  $000055E7A02525BE
  $000055E7A044DC33
  $000055E7A0252514
[FORMS.PP] ExceptionOccurred 
`
Hope that helps.

**Comment by circular17** [comment]
Hmmm that looks like an issue between the program and the widget set. I will try on a VM to fix it

**Comment by zeroheure** [comment]
Similar behaviour here on Debian Sid (up to date). 
How can I launch Lazpaint with debug options ?

**Comment by circular17** [comment]
One way would be to compile it yourself. Here's how.

Install Lazarus package.
Download the source code of LazPaint, for example from upstream:
https://github.com/bgrabitmap/lazpaint-upstream
Then run Lazarus. 
With all necessary packages (bgrabitmap, bgracontrols, lazpaintcontrols)
- open using package menu and find LPK file
- go into package options, go to link options and set optimization level 0, in debug options check generate debug info
Then open LazPaint project (lazpaint.lpi)
Choose build mode Debug (next to Play button there is a config button, click the dropdown arrow, then choose)
Then click the Play button
You should get LazPaint running. If an error occurs, it will stop and show the line causing the problem. You can also open the stack trace with menu View > Debug window

Otherwise I will try to provide debug binaries

**Comment by circular17** [comment]
Here are debug binaries:
https://github.com/bgrabitmap/lazpaint/releases/download/v7.2.2/lazpaint7.2.2_linux64_gtk2_debug.tar.gz

**Comment by circular17** [comment]
I've tried on a virtual machine with xUbuntu 22.04.1 and resampled an image without issue. Can you provide a sample image that I can try to resample and steps to reproduce the bug?

**Comment by zeroheure** [comment]
Breaking news ! it only happened on the Lazpaint Qt5 version. Sorry, I didn't even knows that there is two versions. The GTK2 version works fine for me, no crash, no exception at startup.

**Comment by circular17** [comment]
Thanks for the detailed answer. I understand we are not always available.

Xfce is kind of related to Gtk so it makes sense it would be more compatible. Though there may be some way to avoid the crash with Qt5.

Ok I was able to reproduce the two bugs with Qt5 version. It it related to timer events.

**Comment by circular17** [comment]
I found a way to avoid the bugs by removing the yellow popup about action progress. Here is a fixed version for Qt5 :
https://github.com/bgrabitmap/lazpaint/releases/download/v7.2.2/lazpaint7.2.2_linux64_qt5_bugfix.tar.gz

**Comment by zeroheure** [comment]
Tested, everything ok
- no exception at startup
- no crash after canvas resize or resample

Thanks for the good job Johann !

**Comment by circular17** [comment]
You're very welcome

Thanks for helping me finding the bugs !
