### ISSUE TITLE
debian package in sid, version 7.2.2.1

### ISSUE THREAD

**Issue by alexmyczko** [bgrabitmap/lazpaint#574]
the reason to have a version is the orig.tar.gz was changed and i packed it as orig.tar.xz

**Comment by circular17** [comment]
Hello Alex,

I am not sure to understand what is your point. Which of the possibilities do you find more adapted:
- keep as you did already, having a package 7.2.2.1 on Debian even though the software considers itself as 7.2.2
- tweak the source code, so that the software displays 7.2.2.1, so one can confirm they have the updated Debian package
- make a release on the upstream only with version 7.2.2.1, this may raise some warnings when comparing with source repository still being at version 7.2.2
- make an official release with version 7.2.2.1, the drawback behind that users would falsely believe it is a new version

Regards

**Comment by circular17** [comment]
Also, is there a reason to increment to version 7.2.2.1 instead of 7.2.2-3?

**Comment by alexmyczko** [comment]
Yes because the tarball of 7.2.2 does not have the commits you did after that release?

**Comment by circular17** [comment]
Ok. So let's keep verion 7.2.2.1 to be consistent with your change.

What option do you prefer (among the 4 options)?

**Comment by alexmyczko** [comment]
first one

**Comment by circular17** [comment]
Ok, thank you for your feedback. I'll consider the issue closed then.
